%YAML:1.0
#common parameters

output_path: "/home/lab/Project/FullRobotSystem/output"  #输出文件夹

#以下是电量充足下，电机的一些经验参数，但是可能随着电量的改变因动力不足，而参数变得不适应--------------------------------
search_wait: 40  #搜索水瓶最低等待时间
warning_distance: 15  #开启预警的超声波检测距离
body_avoid_step: 30   #如果障碍物普遍较大，发现转过之后绕不开障碍物，可以适当增加这个值
nstep_turn_90deg: 11  #旋转90度所需点机次数，如果发现转过头来搜索的时候经常转的太多，很难稳定，适当减小这个参数，反之增加。

searching_direction: -1 #旋转方向  右转，这里是指定水瓶的方向
thes_angle: 0.1047 #M_PI/2是90°，这里是偏航最大允许的角度M_PI/30
win_size_direction: 5 #位姿频率是10Hz，也就是100ms刷新一次航向，航向与预先规定方向夹角的正弦值为sin_x,其滑动窗口大小为win_size_direction，保留5帧航向夹角正弦值
distance_thes: 30 #避障传感器的避障距离，小于该值开始转向避障

obs_min: 130 #双目相机避障参数，深度图中将距离分为0~255，数值越大距离越近，深度图中像素范围落在 obs_min～255 中的值将认定为障碍物像素

Kp: 2.6 #航向调整的pid
Ki: 0.3 #航向调整的pid
Kd: 0.35 #航向调整的pid

max_delta_u: 1.5 #电机输出限幅
min_delta_u: 0.04 #电机输出限幅

# 预设三个瓶子与小车其起跑线的垂直距离
bottle_1: 1.2
bottle_2: 2.5
bottle_3: 3.5

###搜索水瓶相关
water_line_win: 2  #为了防止干扰，设置最小需要有这么多的次数的帧检测到液面，才最终断定有水
water_line_thres: 0.6 #线长大于该比例的水瓶宽度就认定为是水平线，如果对水平线检测过于敏感或者不够敏感，应该向下或者向上调节这个值
